spring.application.name=code-runner-service

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1s

rabbitmq.code-execution.success-queue-name=code-execution-success-queue
rabbitmq.code-execution.failed-queue-name=code-execution-failed-queue
rabbitmq.code-execution.exchange-name=code-execution-exchange
rabbitmq.code-execution.success-routing-key=code-execution-success-key
rabbitmq.code-execution.failed-routing-key=code-execution-failed-key
rabbitmq.code-execution.queue=code-execution-queue


docker-containers.pool.java.size=2
docker-containers.pool.java.image-name=amazoncorretto:17-alpine
