spring.application.name=code-runner-service

# H2 in-memory for development
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:coderunner}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=secure_password
spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1s

rabbitmq.code-execution.request-queue-name=code-execution-requests
rabbitmq.code-execution.result-queue-name=code-execution-results
rabbitmq.code-execution.exchange-name=code-execution-exchange
rabbitmq.code-execution.request-routing-key=code-execution-requests-key
rabbitmq.code-execution.result-routing-key=code-execution-results-key


management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}

docker-containers.pool.java.size=2
docker-containers.pool.java.image-name=amazoncorretto:17-alpine
docker-containers.pool.python.size=2
docker-containers.pool.python.image-name=python:3.11-alpine
docker-containers.pool.cpp.size=2
docker-containers.pool.cpp.image-name=gcc:13-alpine
docker-containers.pool.csharp.size=2
docker-containers.pool.csharp.image-name=mcr.microsoft.com/dotnet/sdk:8.0-alpine
docker-containers.pool.go.size=2
docker-containers.pool.go.image-name=golang:1.22-alpine
